
import { Product } from './types';

// Helper to generate placeholder images that look like products
const getProductImage = (name: string, type: 'Cotton' | 'Polyester') => {
  const bg = type === 'Cotton' ? 'f8fafc' : 'f1f5f9'; // Slightly different backgrounds
  const fg = '0f172a';
  const text = encodeURIComponent(name);
  return `https://placehold.co/600x800/${bg}/${fg}?text=${text}`;
};

export const PRODUCTS: Product[] = [
  // --- COTTON LACES ---
  { id: 'C001', name: '1 Line Cotton Heavy P.P.', category: 'Cotton', image: getProductImage('1 Line Cotton Heavy P.P.', 'Cotton') },
  { id: 'C002', name: '1 Line Cotton Black Heavy', category: 'Cotton', image: getProductImage('1 Line Cotton Black Heavy', 'Cotton') },
  { id: 'C003', name: '1 Line Cotton Gray Heavy', category: 'Cotton', image: getProductImage('1 Line Cotton Gray Heavy', 'Cotton') },
  { id: 'C004', name: '1 Live Cotton Heavy White', category: 'Cotton', image: getProductImage('1 Live Cotton Heavy White', 'Cotton') },
  { id: 'C005', name: '1 Line Black Light', category: 'Cotton', image: getProductImage('1 Line Black Light', 'Cotton') },
  { id: 'C006', name: '1 Line Gray Light', category: 'Cotton', image: getProductImage('1 Line Gray Light', 'Cotton') },
  { id: 'C007', name: '1 Line White Light', category: 'Cotton', image: getProductImage('1 Line White Light', 'Cotton') },
  { id: 'C008', name: 'Single Button Mindi Gray', category: 'Cotton', image: getProductImage('Single Button Mindi Gray', 'Cotton') },
  { id: 'C009', name: 'Single Button Mindi White', category: 'Cotton', image: getProductImage('Single Button Mindi White', 'Cotton') },
  { id: 'C010', name: 'Double Button Mindi White', category: 'Cotton', image: getProductImage('Double Button Mindi White', 'Cotton') },
  { id: 'C011', name: '2 Line Cotton Full Heavy', category: 'Cotton', image: getProductImage('2 Line Cotton Full Heavy', 'Cotton') },
  { id: 'C012', name: '2 Line Black Heavy', category: 'Cotton', image: getProductImage('2 Line Black Heavy', 'Cotton') },
  { id: 'C013', name: '2 Line Black M.H.', category: 'Cotton', image: getProductImage('2 Line Black M.H.', 'Cotton') },
  { id: 'C014', name: '2 Line White M.H.', category: 'Cotton', image: getProductImage('2 Line White M.H.', 'Cotton') },
  { id: 'C015', name: '2 Line Cotton Light', category: 'Cotton', image: getProductImage('2 Line Cotton Light', 'Cotton') },
  { id: 'C016', name: 'Black Chameli', category: 'Cotton', image: getProductImage('Black Chameli', 'Cotton') },
  { id: 'C017', name: 'White Chameli', category: 'Cotton', image: getProductImage('White Chameli', 'Cotton') },
  { id: 'C018', name: 'White Cotton Eight', category: 'Cotton', image: getProductImage('White Cotton Eight', 'Cotton') },
  { id: 'C019', name: 'White Cotton Vak', category: 'Cotton', image: getProductImage('White Cotton Vak', 'Cotton') },
  { id: 'C020', name: 'Double Border 3 Line Gray Heavy', category: 'Cotton', image: getProductImage('Double Border 3 Line Gray', 'Cotton') },
  { id: 'C021', name: 'Double Border 3 Line White', category: 'Cotton', image: getProductImage('Double Border 3 Line White', 'Cotton') },
  { id: 'C022', name: 'Double Border 3 Line Black', category: 'Cotton', image: getProductImage('Double Border 3 Line Black', 'Cotton') },
  { id: 'C023', name: 'Double Border 3 Line Gray Light', category: 'Cotton', image: getProductImage('Double Border 3 Line Gray Lt', 'Cotton') },
  { id: 'C024', name: '3 Line Cotton Heavy', category: 'Cotton', image: getProductImage('3 Line Cotton Heavy', 'Cotton') },
  { id: 'C025', name: '3 Line Cotton Black Heavy', category: 'Cotton', image: getProductImage('3 Line Cotton Black Heavy', 'Cotton') },
  { id: 'C026', name: '3 Line Cotton White Light', category: 'Cotton', image: getProductImage('3 Line Cotton White Light', 'Cotton') },
  { id: 'C027', name: 'White Poonam Heavy', category: 'Cotton', image: getProductImage('White Poonam Heavy', 'Cotton') },
  { id: 'C028', name: 'Black Poonam Heavy', category: 'Cotton', image: getProductImage('Black Poonam Heavy', 'Cotton') },
  { id: 'C029', name: 'Gray Poonam Heavy', category: 'Cotton', image: getProductImage('Gray Poonam Heavy', 'Cotton') },
  { id: 'C030', name: 'While Poonam Light', category: 'Cotton', image: getProductImage('White Poonam Light', 'Cotton') },
  { id: 'C031', name: 'Gray Poonam Jari', category: 'Cotton', image: getProductImage('Gray Poonam Jari', 'Cotton') },
  { id: 'C032', name: 'White Poonam Silver', category: 'Cotton', image: getProductImage('White Poonam Silver', 'Cotton') },
  { id: 'C033', name: 'Black Poonam Jari', category: 'Cotton', image: getProductImage('Black Poonam Jari', 'Cotton') },
  { id: 'C034', name: 'White Poonam Jari LG', category: 'Cotton', image: getProductImage('White Poonam Jari LG', 'Cotton') },
  { id: 'C035', name: 'White CD Jari', category: 'Cotton', image: getProductImage('White CD Jari', 'Cotton') },
  { id: 'C036', name: 'Gray CD Heavy', category: 'Cotton', image: getProductImage('Gray CD Heavy', 'Cotton') },
  { id: 'C037', name: 'White CD Heavy', category: 'Cotton', image: getProductImage('White CD Heavy', 'Cotton') },
  { id: 'C038', name: 'Gray CD Light', category: 'Cotton', image: getProductImage('Gray CD Light', 'Cotton') },
  { id: 'C039', name: 'White CD Light', category: 'Cotton', image: getProductImage('White CD Light', 'Cotton') },
  { id: 'C040', name: 'Black Cotton Mandir', category: 'Cotton', image: getProductImage('Black Cotton Mandir', 'Cotton') },
  { id: 'C041', name: 'Gray Cotton Mandir', category: 'Cotton', image: getProductImage('Gray Cotton Mandir', 'Cotton') },
  { id: 'C042', name: 'White Cotton Mandir', category: 'Cotton', image: getProductImage('White Cotton Mandir', 'Cotton') },
  { id: 'C043', name: 'White Cotton Double M', category: 'Cotton', image: getProductImage('White Cotton Double M', 'Cotton') },
  { id: 'C044', name: '507 White Heavy', category: 'Cotton', image: getProductImage('507 White Heavy', 'Cotton') },
  { id: 'C045', name: '507 Black', category: 'Cotton', image: getProductImage('507 Black', 'Cotton') },
  { id: 'C046', name: '507 Gray', category: 'Cotton', image: getProductImage('507 Gray', 'Cotton') },
  { id: 'C047', name: '507 White Light', category: 'Cotton', image: getProductImage('507 White Light', 'Cotton') },
  { id: 'C048', name: '507 Black & White', category: 'Cotton', image: getProductImage('507 Black & White', 'Cotton') },
  { id: 'C049', name: '507 White & Black', category: 'Cotton', image: getProductImage('507 White & Black', 'Cotton') },
  { id: 'C050', name: '507 Gray Jari', category: 'Cotton', image: getProductImage('507 Gray Jari', 'Cotton') },
  { id: 'C051', name: '507 Gray Copper Jari', category: 'Cotton', image: getProductImage('507 Gray Copper Jari', 'Cotton') },
  { id: 'C052', name: '507 White Jari', category: 'Cotton', image: getProductImage('507 White Jari', 'Cotton') },
  { id: 'C053', name: '507 White Copper Jari', category: 'Cotton', image: getProductImage('507 White Copper Jari', 'Cotton') },
  { id: 'C054', name: 'White Cotton Dream Mandir', category: 'Cotton', image: getProductImage('White Cotton Dream Mandir', 'Cotton') },
  { id: 'C055', name: 'Cotton 2 Line Dekor', category: 'Cotton', image: getProductImage('Cotton 2 Line Dekor', 'Cotton') },
  { id: 'C056', name: '1 Line Dekor', category: 'Cotton', image: getProductImage('1 Line Dekor', 'Cotton') },
  { id: 'C057', name: '1 Line Dekor Black', category: 'Cotton', image: getProductImage('1 Line Dekor Black', 'Cotton') },
  { id: 'C058', name: 'Gray Dadar Cotton', category: 'Cotton', image: getProductImage('Gray Dadar Cotton', 'Cotton') },
  { id: 'C059', name: 'White Dadar Cotton', category: 'Cotton', image: getProductImage('White Dadar Cotton', 'Cotton') },
  { id: 'C060', name: 'Black Dadar Cotton', category: 'Cotton', image: getProductImage('Black Dadar Cotton', 'Cotton') },
  { id: 'C061', name: '425 White Heavy', category: 'Cotton', image: getProductImage('425 White Heavy', 'Cotton') },
  { id: 'C062', name: '425 Gray', category: 'Cotton', image: getProductImage('425 Gray', 'Cotton') },
  { id: 'C063', name: '425 White', category: 'Cotton', image: getProductImage('425 White', 'Cotton') },
  { id: 'C064', name: 'Cotton Gray Fumki', category: 'Cotton', image: getProductImage('Cotton Gray Fumki', 'Cotton') },
  { id: 'C065', name: 'Cotton White Fumki', category: 'Cotton', image: getProductImage('Cotton White Fumki', 'Cotton') },
  { id: 'C066', name: 'Cotton Rimzim Gray', category: 'Cotton', image: getProductImage('Cotton Rimzim Gray', 'Cotton') },
  { id: 'C067', name: 'Cotton Rimzim White', category: 'Cotton', image: getProductImage('Cotton Rimzim White', 'Cotton') },
  { id: 'C068', name: 'Gray Cutting', category: 'Cotton', image: getProductImage('Gray Cutting', 'Cotton') },
  { id: 'C069', name: 'White Cutting', category: 'Cotton', image: getProductImage('White Cutting', 'Cotton') },
  { id: 'C070', name: 'Cotton Gray Apple', category: 'Cotton', image: getProductImage('Cotton Gray Apple', 'Cotton') },
  { id: 'C071', name: 'Cotton White Apple', category: 'Cotton', image: getProductImage('Cotton White Apple', 'Cotton') },
  { id: 'C072', name: 'Cotton Sanam Jari', category: 'Cotton', image: getProductImage('Cotton Sanam Jari', 'Cotton') },
  { id: 'C073', name: 'Cotton Hariyali', category: 'Cotton', image: getProductImage('Cotton Hariyali', 'Cotton') },
  { id: 'C074', name: 'Cotton Full Racket', category: 'Cotton', image: getProductImage('Cotton Full Racket', 'Cotton') },
  { id: 'C075', name: 'Saiyara White', category: 'Cotton', image: getProductImage('Saiyara White', 'Cotton') },

  // --- POLYESTER LACES ---
  { id: 'P001', name: 'Black Taj Mahel', category: 'Polyester', image: getProductImage('Black Taj Mahel', 'Polyester') },
  { id: 'P002', name: 'White Taj Mahel Light', category: 'Polyester', image: getProductImage('White Taj Mahel Light', 'Polyester') },
  { id: 'P003', name: 'FDY Poonam', category: 'Polyester', image: getProductImage('FDY Poonam', 'Polyester') },
  { id: 'P004', name: 'Double Mindi Water Heavy', category: 'Polyester', image: getProductImage('Double Mindi Water Heavy', 'Polyester') },
  { id: 'P005', name: 'Choch Kaju Golden', category: 'Polyester', image: getProductImage('Choch Kaju Golden', 'Polyester') },
  { id: 'P006', name: 'Choch Kaju Jari', category: 'Polyester', image: getProductImage('Choch Kaju Jari', 'Polyester') },
  { id: 'P007', name: 'Choch Kaju Water', category: 'Polyester', image: getProductImage('Choch Kaju Water', 'Polyester') },
  { id: 'P008', name: 'Choch Kaju White', category: 'Polyester', image: getProductImage('Choch Kaju White', 'Polyester') },
  { id: 'P009', name: '3 Line Bullet', category: 'Polyester', image: getProductImage('3 Line Bullet', 'Polyester') },
  { id: 'P010', name: 'Chenaram', category: 'Polyester', image: getProductImage('Chenaram', 'Polyester') },
  { id: 'P011', name: 'P.P. Divdo', category: 'Polyester', image: getProductImage('P.P. Divdo', 'Polyester') },
  { id: 'P012', name: 'Choch Pum Pum', category: 'Polyester', image: getProductImage('Choch Pum Pum', 'Polyester') },
  { id: 'P013', name: 'Double Mindi', category: 'Polyester', image: getProductImage('Double Mindi', 'Polyester') },
  { id: 'P014', name: 'V.M. Button', category: 'Polyester', image: getProductImage('V.M. Button', 'Polyester') },
  { id: 'P015', name: 'V.M. Heavy', category: 'Polyester', image: getProductImage('V.M. Heavy', 'Polyester') },
  { id: 'P016', name: 'V.M. Light', category: 'Polyester', image: getProductImage('V.M. Light', 'Polyester') },
  { id: 'P017', name: 'V.M. Silver', category: 'Polyester', image: getProductImage('V.M. Silver', 'Polyester') },
  { id: 'P018', name: 'V.M. White', category: 'Polyester', image: getProductImage('V.M. White', 'Polyester') },
  { id: 'P019', name: 'Dilpan Jari', category: 'Polyester', image: getProductImage('Dilpan Jari', 'Polyester') },
  { id: 'P020', name: 'Dilpan White', category: 'Polyester', image: getProductImage('Dilpan White', 'Polyester') },
  { id: 'P021', name: 'P.P. CD', category: 'Polyester', image: getProductImage('P.P. CD', 'Polyester') },
  { id: 'P022', name: '1 Line Mindi', category: 'Polyester', image: getProductImage('1 Line Mindi', 'Polyester') },
  { id: 'P023', name: 'Double Button Divdo', category: 'Polyester', image: getProductImage('Double Button Divdo', 'Polyester') },
  { id: 'P024', name: 'Fancy Divdo', category: 'Polyester', image: getProductImage('Fancy Divdo', 'Polyester') },
  { id: 'P025', name: 'FDY Nagin J', category: 'Polyester', image: getProductImage('FDY Nagin J', 'Polyester') },
  { id: 'P026', name: 'Jari Taj Mahel', category: 'Polyester', image: getProductImage('Jari Taj Mahel', 'Polyester') },
  { id: 'P027', name: 'Silver Jari Taj Mahel', category: 'Polyester', image: getProductImage('Silver Jari Taj Mahel', 'Polyester') },
  { id: 'P028', name: 'White Taj Mahel Heavy', category: 'Polyester', image: getProductImage('White Taj Mahel Heavy', 'Polyester') },
  { id: 'P029', name: 'Jari Athdo', category: 'Polyester', image: getProductImage('Jari Athdo', 'Polyester') },
  { id: 'P030', name: 'Jari 1 Line', category: 'Polyester', image: getProductImage('Jari 1 Line', 'Polyester') },
  { id: 'P031', name: 'Button Divdo', category: 'Polyester', image: getProductImage('Button Divdo', 'Polyester') },
  { id: 'P032', name: 'White Divdo', category: 'Polyester', image: getProductImage('White Divdo', 'Polyester') },
  { id: 'P033', name: 'Button Divdo LG', category: 'Polyester', image: getProductImage('Button Divdo LG', 'Polyester') },
  { id: 'P034', name: 'Cotton Divdo Silver', category: 'Polyester', image: getProductImage('Cotton Divdo Silver', 'Polyester') },
  { id: 'P035', name: 'Button Divdo Light', category: 'Polyester', image: getProductImage('Button Divdo Light', 'Polyester') },
  { id: 'P036', name: 'FDY Deep', category: 'Polyester', image: getProductImage('FDY Deep', 'Polyester') },
  { id: 'P037', name: 'FDY Chokdi', category: 'Polyester', image: getProductImage('FDY Chokdi', 'Polyester') },
  { id: 'P038', name: 'Ramjane Full Heavy', category: 'Polyester', image: getProductImage('Ramjane Full Heavy', 'Polyester') },
  { id: 'P039', name: 'P.P. Ramjane', category: 'Polyester', image: getProductImage('P.P. Ramjane', 'Polyester') },
  { id: 'P040', name: 'Ramjane LG', category: 'Polyester', image: getProductImage('Ramjane LG', 'Polyester') },
  { id: 'P041', name: 'Ramjane Water', category: 'Polyester', image: getProductImage('Ramjane Water', 'Polyester') },
  { id: 'P042', name: 'Ramjane Light', category: 'Polyester', image: getProductImage('Ramjane Light', 'Polyester') },
  { id: 'P043', name: 'FDY Hariyali', category: 'Polyester', image: getProductImage('FDY Hariyali', 'Polyester') },
  { id: 'P044', name: 'Ulti Mindi', category: 'Polyester', image: getProductImage('Ulti Mindi', 'Polyester') },
  { id: 'P045', name: 'Welcme LG', category: 'Polyester', image: getProductImage('Welcme LG', 'Polyester') },
  { id: 'P046', name: 'Welcome Water', category: 'Polyester', image: getProductImage('Welcome Water', 'Polyester') },
  { id: 'P047', name: 'Welcome Silver', category: 'Polyester', image: getProductImage('Welcome Silver', 'Polyester') },
  { id: 'P048', name: 'Welcome White', category: 'Polyester', image: getProductImage('Welcome White', 'Polyester') },
  { id: 'P049', name: '2 Inch Jadu', category: 'Polyester', image: getProductImage('2 Inch Jadu', 'Polyester') },
  { id: 'P050', name: '5 Inch Jadu', category: 'Polyester', image: getProductImage('5 Inch Jadu', 'Polyester') },
  { id: 'P051', name: '3 Inch Jadu', category: 'Polyester', image: getProductImage('3 Inch Jadu', 'Polyester') },
  { id: 'P052', name: 'Choch W Heavy', category: 'Polyester', image: getProductImage('Choch W Heavy', 'Polyester') },
  { id: 'P053', name: 'Choch W Light', category: 'Polyester', image: getProductImage('Choch W Light', 'Polyester') },
  { id: 'P054', name: 'Choch W Silver', category: 'Polyester', image: getProductImage('Choch W Silver', 'Polyester') },
  { id: 'P055', name: 'Choch W White', category: 'Polyester', image: getProductImage('Choch W White', 'Polyester') },
  { id: 'P056', name: 'P.P. Nagin', category: 'Polyester', image: getProductImage('P.P. Nagin', 'Polyester') },
  { id: 'P057', name: 'Double Border 3 Line P.P.', category: 'Polyester', image: getProductImage('Dbl Border 3 Line P.P.', 'Polyester') },
  { id: 'P058', name: '3 Line Polyester Heavy', category: 'Polyester', image: getProductImage('3 Line Poly Heavy', 'Polyester') },
  { id: 'P059', name: '2 Line Polyester Heavy', category: 'Polyester', image: getProductImage('2 Line Poly Heavy', 'Polyester') },
  { id: 'P060', name: '3 Line Polyester Light', category: 'Polyester', image: getProductImage('3 Line Poly Light', 'Polyester') },
  { id: 'P061', name: '2 Line Polyester Light', category: 'Polyester', image: getProductImage('2 Line Poly Light', 'Polyester') },
  { id: 'P062', name: '2 Line Polyester Dori', category: 'Polyester', image: getProductImage('2 Line Poly Dori', 'Polyester') },
  { id: 'P063', name: 'Multi Poonam', category: 'Polyester', image: getProductImage('Multi Poonam', 'Polyester') },
  { id: 'P064', name: 'Multi 1 Line', category: 'Polyester', image: getProductImage('Multi 1 Line', 'Polyester') },
  { id: 'P065', name: 'Choch Bullet Multi', category: 'Polyester', image: getProductImage('Choch Bullet Multi', 'Polyester') },
  { id: 'P066', name: 'Choch Bullet Black Multi', category: 'Polyester', image: getProductImage('Choch Bullet Black Mul', 'Polyester') },
  { id: 'P067', name: 'Choch Bullet White', category: 'Polyester', image: getProductImage('Choch Bullet White', 'Polyester') },
  { id: 'P068', name: 'Choch Bullet Black', category: 'Polyester', image: getProductImage('Choch Bullet Black', 'Polyester') },
  { id: 'P069', name: 'Single Choch', category: 'Polyester', image: getProductImage('Single Choch', 'Polyester') },
  { id: 'P070', name: 'Saiyara Gray', category: 'Polyester', image: getProductImage('Saiyara Gray', 'Polyester') },
  { id: 'P071', name: 'Black CD Light', category: 'Polyester', image: getProductImage('Black CD Light', 'Polyester') },
  { id: 'P072', name: 'Double Mindi Water Light', category: 'Polyester', image: getProductImage('Dbl Mindi Water Light', 'Polyester') },
  { id: 'P073', name: 'Choch W Chiku', category: 'Polyester', image: getProductImage('Choch W Chiku', 'Polyester') },
];

export const COMPANY_INFO = {
  name: "Gurukrupa Exports International",
  phone: "+91-9979504265",
  whatsapp_clean: "919979504265",
  email: "exports@gurukrupanerofab.com",
  address: "Flat No. 41, Floor No. 1 ST FL, Somnath Industrial Park, Devadh Gam, Surat, Gujarat-394210, India",
  established: "2012"
};
